### PR TITLE
Css canvas medical Ryan Byrnes

### PR DESCRIPTION
**Pull request by ryan-byrnes**
Screen Shot 2021-06-29 at 8 58 45 PM
Screen Shot 2021-06-29 at 8 59 02 PM
Screen Shot 2021-06-29 at 8 59 11 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Ryan!! This is looking great so far, just one issue: Your buttons have a border that is not visible in the example output, please remove those, and make sure you upload a new screenshot after you have revised

**Comment by ryan-byrnes** [comment]
Screen Shot 2021-07-01 at 5 38 17 PM
Screen Shot 2021-07-01 at 5 38 36 PM
Screen Shot 2021-07-01 at 5 38 49 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey dude!! A couple notes for you:

1. Your hero image is a bit too tall as compared to the example, and the general text inside of it seems a bit too bold
2. The text below the headline in the section with the list of locations should be center-aligned, but it is left-aligned

**Comment by ryan-byrnes** [comment]
Screen Shot 2021-07-05 at 9 46 13 AM
Screen Shot 2021-07-05 at 9 46 32 AM
Screen Shot 2021-07-05 at 9 46 44 AM

**Review by codingcodymiller — APPROVED** [review]
Great job on this!!

**Pull request merged**
