### PR TITLE
Completed CSS e-commerce page Ryan Byrnes

### PR DESCRIPTION
**Pull request by ryan-byrnes**
Screen Shot 2021-07-01 at 3 13 33 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Ryan! Your line between the brand and size is the wrong color, and you seem to be missing the peach colored box around the current price, please revise

**Comment by ryan-byrnes** [comment]
Screen Shot 2021-07-01 at 5 54 15 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey dude, it shouldn't be a peach border, it should be a peach background color with rounded borders, I would take a closer look at the example image to get a better idea of what we're looking for

**Comment by ryan-byrnes** [comment]
Screen Shot 2021-07-02 at 11 38 37 AM

**Review by codingcodymiller — APPROVED** [review]
Great job on this!!

**Pull request merged**
